image: ghcr.io/labsyspharm/mcmicro:devenv-latest
tasks:
  - name: Download default containers
    init: |
      python -c "import yaml;\
        mcp = yaml.safe_load(open('config/defaults.yml'));\
        mods = mcp['modules'];\
        [print(m['container'] + ':' + m['version']) for m in \
          [mods['registration'], mods['segmentation'][0],\
           mods['watershed'], mods['quantification']]]"\
      | while read line ; do docker pull $line ; done
  - name: Default workdir
    init: cd /workspace
