# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 3.9.2"
gem "rake", "~> 13.0"
gem "html-proofer", "~> 4.3"
gem "github-pages", "~>227", group: :jekyll_plugins


group :jekyll_plugins do
    gem 'jekyll-seo-tag'
    gem 'jekyll-remote-theme'
    gem 'jekyll-include-cache'
    gem 'jekyll-redirect-from'
  end
