name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - roadie/Dockerfile
      - modules/auto-minerva/Dockerfile

jobs:
  docker:
    strategy:
      matrix:
        include:
          - name: roadie
            context: roadie
          - name: auto-minerva
            context: modules/auto-minerva
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          push: true
          tags: labsyspharm/${{ matrix.name }}:${{ steps.date.outputs.date }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
