name: O2-CI

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md
      - CHANGES.md
      - .gitpod.yml
      - 'docs/**'
      - 'setup/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test:
    runs-on: O2
    steps:
      - uses: actions/checkout@v3
      - name: Test on exemplars
        run: |
          module load java
          nextflow main.nf --in ~/exemplar-001 -profile O2
          nextflow main.nf --in ~/exemplar-002 -profile O2
