name: roadie

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'modules/roadie/Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: modules/roadie
          push: true
          tags: labsyspharm/roadie:${{ steps.date.outputs.date }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
